apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.name }}
  labels:
    app: {{ .Values.ingress.name }}
spec:
  tls:
    termination: edge
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            backend:
              service: 
                name: {{ .Chart.name }}
                port: {{ .Values.service.externalPort }}